import Head from 'next/head'
import Image from 'next/image'
import CardAgents from '../components/CardAgents';
import Navbar from '../components/Navbar';
import styles from '../styles/Home.module.scss';
import Button from '../components/Button';
import { Swiper, SwiperSlide } from 'swiper/react';
import 'swiper/css';
import "swiper/css/navigation";
import { Navigation } from "swiper";


export default function Home({ list }) {
  console.log(list)
  return (
    <div className={`${styles.container} container mx-auto`}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} antialiased`}>
          <Navbar />
          <div className={`${styles.banner} border border-gray-500 rounded-lg mt-9 grid grid-cols-2 relative`}>
              <div className={`${styles.info} flex-col`}>
                <h1 className="mb-4 antialiased">Valorant: o FPS <br></br>
                  competitivo 5x5
                </h1>
                <p className="antialiased">Um FPS tático 5x5 com personagens marcantes, mecânica de tiro precisa e <br></br>
                habilidades únicas! 
                </p>
                <Button href="./sobre">
                  SAIBA MAIS
                </Button>
              </div>
              <img src="/img/banner.png" className={`${styles.imgBanner} absolute`} />
          </div>
          <Swiper navigation={true} modules={[Navigation]} className={styles.card}
            slidesPerView={4}
          > 
            {list.map( item => {
              if(item.isPlayableCharacter) 
                return (<SwiperSlide key={item.uuid}><CardAgents item={item} /></SwiperSlide>)
            })}
        </Swiper>
      </main>
    </div>
  )
}

  export async function getStaticProps() {
  const res = await fetch('http://localhost:3000/api/agents');
  const json = await res.json();

  return {
    props: {
      list: json.list,

    }
  };
}
